### ISSUE TITLE
Passing query to ais-configure doesnt work.

### ISSUE THREAD

**Issue by ivanushkaPr** [meilisearch/meilisearch-vue#135]
**Description**
Hello guys! Im new to meli search and angolia, but seems like i cannot pass search query to meli search cloud provider via ais-configure query.

Im tryed to pass it via query atttribute, and a q attribute like meli search documentation  said, but there is no query parameter in cloud response.

Can you tell what i am doing wrong or its a bug, related to algolia or other packages?

**Expected behavior**
Passing query as prop to ais configure leads to return of items filtered by that value.

**Current behavior**
Query doesnt passed to request.

**Minimal reproduction example**
https://stackblitz.com/edit/vue-gjznih?file=src%2FApp.vue,src%2Fmain.js

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Windows 11
- Browser: Chrome 121.0.6167.139 
- Meilisearch version: Im using cloud.
- instant-meilisearch version:  ^0.14.0,
- vue-instantsearch version: ^4.13.2,
- Vue.js version: vue@3.3.13

**Comment by curquiza** [comment]
Hello @ivanushkaPr 

Looks like your issue is more related to a support need and not a request for feature or a bug fix. At least we need more investigation before saying it's a real bug report. But most of all you need quick support to help you play with Meilisearch 😁

We are a small team, so we can’t spend much time doing support this specific repo :cry:
You might have noticed when opening the issue we don't do support in this repo anymore.

<img width="1230" alt="Capture d’écran 2023-10-11 à 16 56 38" src="https://github.com/meilisearch/meilisearch-java/assets/20380692/d32e8d6f-9bb3-4bdb-89fd-85ebb4572f0f">

So, if you want immediate help, we would recommend going to our [Discord](https://discord.gg/meilisearch) instead. The community will be able to help you, no matter your question.

Thanks for using Meilisearch!
